//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class accuracy
    {
        public int id { get; set; }
        public int original_document_id { get; set; }
        public int updated_document_id { get; set; }
        public int job_id { get; set; }
        public int accuracy_type_id { get; set; }
        public decimal percent_change { get; set; }
        public decimal accuracy_percentage { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual accuracy_type accuracy_type { get; set; }
        public virtual job job { get; set; }
        public virtual document document { get; set; }
        public virtual document document1 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
