//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public address()
        {
            this.entities = new HashSet<entity>();
            this.billing_info = new HashSet<billing_info>();
            this.contacts = new HashSet<contact>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string mail_address1 { get; set; }
        public string mail_address2 { get; set; }
        public string mail_city { get; set; }
        public Nullable<int> mail_state_id { get; set; }
        public string mail_postal_code { get; set; }
        public Nullable<int> mail_country_id { get; set; }
        public string phys_address1 { get; set; }
        public string phys_address2 { get; set; }
        public string phys_city { get; set; }
        public Nullable<int> phys_state_id { get; set; }
        public string phys_postal_code { get; set; }
        public Nullable<int> phys_country_id { get; set; }
        public string main_phone_number { get; set; }
        public string main_fax_number { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int last_modified_by { get; set; }
        public int created_by { get; set; }
        public bool delete_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entity> entities { get; set; }
        public virtual user user { get; set; }
        public virtual address_country address_country { get; set; }
        public virtual address_state address_state { get; set; }
        public virtual user user1 { get; set; }
        public virtual address_country address_country1 { get; set; }
        public virtual address_state address_state1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billing_info> billing_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact> contacts { get; set; }
    }
}
