//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_log
    {
        public int id { get; set; }
        public System.DateTime log_stamp { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> relationship_id { get; set; }
        public string table_name { get; set; }
        public string table_id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> oauth_client_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public string action { get; set; }
        public string remarks { get; set; }
        public string mrn { get; set; }
        public string subject_last { get; set; }
        public string subject_first { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string pid { get; set; }
        public string web_server { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int last_modified_by { get; set; }
        public int created_by { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual user user { get; set; }
        public virtual entity entity { get; set; }
        public virtual job job { get; set; }
        public virtual user user1 { get; set; }
        public virtual oauth_client oauth_client { get; set; }
        public virtual relationship relationship { get; set; }
        public virtual user user2 { get; set; }
    }
}
