//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class asp_net_user_claim
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string claim_type { get; set; }
        public string claim_value { get; set; }
    
        public virtual user user { get; set; }
    }
}
