//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public billing_info()
        {
            this.entities = new HashSet<entity>();
        }
    
        public int id { get; set; }
        public byte[] card_number { get; set; }
        public string card_type { get; set; }
        public string name_on_card { get; set; }
        public string expiration_date { get; set; }
        public int billing_address_id { get; set; }
        public Nullable<double> line_rate { get; set; }
        public Nullable<double> stat_line_rate { get; set; }
        public Nullable<int> job_line_min { get; set; }
        public Nullable<double> teldoc_rate { get; set; }
        public Nullable<double> job_min { get; set; }
        public Nullable<double> bill_min { get; set; }
        public Nullable<int> line_char { get; set; }
        public Nullable<bool> vbc { get; set; }
        public Nullable<System.DateTime> anniversary_date { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int last_modified_by { get; set; }
        public int created_by { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual address address { get; set; }
        public virtual billing_info billing_info1 { get; set; }
        public virtual billing_info billing_info2 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entity> entities { get; set; }
    }
}
