//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contact()
        {
            this.entities = new HashSet<entity>();
            this.relationships = new HashSet<relationship>();
            this.faxes = new HashSet<fax>();
        }
    
        public int id { get; set; }
        public int address_id { get; set; }
        public string salutation { get; set; }
        public string first_name { get; set; }
        public string mi { get; set; }
        public string last_name { get; set; }
        public string title { get; set; }
        public string direct_phone { get; set; }
        public string phone_ext { get; set; }
        public string direct_fax { get; set; }
        public string fax_ext { get; set; }
        public string mobile_phone { get; set; }
        public string email_address1 { get; set; }
        public string email_address2 { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string comment4 { get; set; }
        public string url { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> relationship_id { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual account account { get; set; }
        public virtual address address { get; set; }
        public virtual entity entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entity> entities { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relationship> relationships { get; set; }
        public virtual relationship relationship { get; set; }
        public virtual user user2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fax> faxes { get; set; }
    }
}
