//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int id { get; set; }
        public string name { get; set; }
        public string device_id { get; set; }
        public int device_platform_id { get; set; }
        public string model { get; set; }
        public string os_version { get; set; }
        public int users_id { get; set; }
        public Nullable<int> pin { get; set; }
        public string app_version { get; set; }
        public System.DateTime date_last_used { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual user user { get; set; }
        public virtual device_platform device_platform { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}
