//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecw_siu_in
    {
        public int id { get; set; }
        public string MSHSendingApplicationName { get; set; }
        public string MSHSendingApplicationID { get; set; }
        public string MSHSendingFacilityNamespaceID { get; set; }
        public string MSHReceivingApplicationEntityName { get; set; }
        public string MSHReceivingApplicationEntityIdentifier { get; set; }
        public string MSHReceivingApplicationEntityIdentifierName { get; set; }
        public Nullable<System.DateTime> MSHDateTimeofMessage { get; set; }
        public string MSHMessageTypeType { get; set; }
        public string MSHMessageTypeEvent { get; set; }
        public string MSHMessageControlID { get; set; }
        public string MSHProcessingIDProcessingType { get; set; }
        public string MSHVersionID { get; set; }
        public string SCHPlacerAppointmentIDEntityIdentifier { get; set; }
        public string SCHFillerAppointmentIDEntityIdentifier { get; set; }
        public string SCHAppointmentReasonIdentifier { get; set; }
        public string SCHAppointmentReason { get; set; }
        public string SCHAppointmentTypeIdentifier { get; set; }
        public string SCHAppointmentTypeText { get; set; }
        public Nullable<double> SCHAppointmentDuration { get; set; }
        public string SCHAppointmentDurationUnitsIdentifier { get; set; }
        public string SCHAppointmentTimingQuantityDuration { get; set; }
        public Nullable<System.DateTime> SCHAppointmentTimingQuantityStartDatetime { get; set; }
        public Nullable<System.DateTime> SCHAppointmentTimingQuantityEndDatetime { get; set; }
        public string SCHEnteredByResourceID { get; set; }
        public string SCHEnteredByResourceName { get; set; }
        public string SCHParentFillerAppointmentEncounterNotes { get; set; }
        public string SCHFillerStatusCodeID { get; set; }
        public string SCHFillerStatusCodeName { get; set; }
        public string PIDSetID { get; set; }
        public string PIDPatientIDInternalIDID { get; set; }
        public string PIDPatientIDExternalIDID { get; set; }
        public string PIDPatientNameFamilyName { get; set; }
        public string PIDPatientNameGivenName { get; set; }
        public string PIDPatientNameMiddleInitialorName { get; set; }
        public Nullable<System.DateTime> PIDDateTimeofBirth { get; set; }
        public string PIDSex { get; set; }
        public string PIDRace { get; set; }
        public string PIDPatientAddressStreetAddress { get; set; }
        public string PIDPatientAddressStreetAddress2 { get; set; }
        public string PIDPatientAddressCity { get; set; }
        public string PIDPatientAddressStateorProvince { get; set; }
        public string PIDPatientAddressZiporpostalcode { get; set; }
        public string PIDPhoneNumberHomeNumber { get; set; }
        public string PIDPhoneNumberHomeEmailAddress { get; set; }
        public string PIDPhoneNumberBusinessNumber { get; set; }
        public string PIDPhoneNumberBusinessCellPhone { get; set; }
        public string PIDPrimaryLanguageIdentifier { get; set; }
        public string PIDMaritalStatus { get; set; }
        public string PIDPatientAccountNumber { get; set; }
        public string PIDPatientSSN { get; set; }
        public string PIDEthnicGroup { get; set; }
        public string PIDDefaultLocation { get; set; }
        public string PIDStatementFlag { get; set; }
        public Nullable<double> PIDStatementSignatureDate { get; set; }
        public string PIDPatientPreviousName { get; set; }
        public string PV1SetID { get; set; }
        public string PV1AssignedPatientLocationLocationCode { get; set; }
        public string PV1AssignedPatientLocationLocationDesc { get; set; }
        public string PV1AttendingDoctorProviderCode { get; set; }
        public string PV1AttendingDoctorLastName { get; set; }
        public string PV1AttendingDoctorFirstName { get; set; }
        public string PV1AttendingDoctorMiddleInitial { get; set; }
        public string PV1AttendingDoctorPrefix { get; set; }
        public string PV1AttendingDoctorSuffix { get; set; }
        public string PV1ReferringDoctorProviderCode { get; set; }
        public string PV1ReferringDoctorLastName { get; set; }
        public string PV1ReferringDoctorFirstName { get; set; }
        public string PV1ReferringDoctorMiddleInitial { get; set; }
        public string PV1ReferringDoctorPrefix { get; set; }
        public string PV1ReferringDoctorSuffix { get; set; }
        public string PV1RenderingProviderProviderCode { get; set; }
        public string PV1RenderingProviderLastName { get; set; }
        public string PV1RenderingProviderFirstName { get; set; }
        public string PV1RenderingProviderMiddleInitial { get; set; }
        public string PV1RenderingProviderPrefix { get; set; }
        public string PV1RenderingProviderSuffix { get; set; }
        public string PV1VisitNumberID { get; set; }
        public Nullable<System.DateTime> PV1AdmitDateTime { get; set; }
        public string PV1AlternateVisitID { get; set; }
        public string AIGSetID { get; set; }
        public string AIGResourceIDIdentifier { get; set; }
        public Nullable<System.DateTime> AIGStartDateTime { get; set; }
        public Nullable<double> AIGDuration { get; set; }
        public string AIGDurationUnitsIdentifier { get; set; }
        public string AILSetID { get; set; }
        public string AILLocationResourceIDPointofCare { get; set; }
        public string AILLocationResourceIDRoom { get; set; }
        public string AIPSetID { get; set; }
        public string AIPOrderingProviderID { get; set; }
        public Nullable<System.DateTime> AIPStartDateTime { get; set; }
        public Nullable<double> AIPDuration { get; set; }
        public string AIPDurationUnits { get; set; }
        public string AIPFillerStatusCode { get; set; }
        public Nullable<int> Entity_ID { get; set; }
    }
}
