//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.abstraction_log = new HashSet<abstraction_log>();
            this.accuracies = new HashSet<accuracy>();
            this.admin_log = new HashSet<admin_log>();
            this.documents = new HashSet<document>();
            this.logs = new HashSet<log>();
            this.job_audio = new HashSet<job_audio>();
            this.job_comment = new HashSet<job_comment>();
            this.nlp_job = new HashSet<nlp_job>();
        }
    
        public int id { get; set; }
        public int entity_id { get; set; }
        public int author_relationship_id { get; set; }
        public Nullable<int> assignee_relationship_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string v_id { get; set; }
        public string c_id { get; set; }
        public string encounter_id { get; set; }
        public System.DateTime submitted_time { get; set; }
        public Nullable<System.DateTime> completed_time { get; set; }
        public Nullable<System.DateTime> to_transcriptionist { get; set; }
        public Nullable<System.DateTime> from_transcriptionist { get; set; }
        public Nullable<System.DateTime> to_editor { get; set; }
        public Nullable<System.DateTime> from_editor { get; set; }
        public Nullable<System.DateTime> to_abstractor { get; set; }
        public Nullable<System.DateTime> from_abstractor { get; set; }
        public Nullable<int> transcription_entity_id { get; set; }
        public Nullable<int> editor_entity_id { get; set; }
        public Nullable<int> abstraction_entity_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> workflow_step_id { get; set; }
        public int priority_id { get; set; }
        public Nullable<System.DateTime> dos { get; set; }
        public string note { get; set; }
        public bool download_flag { get; set; }
        public int download_count { get; set; }
        public bool ehr_return_ready { get; set; }
        public bool alert { get; set; }
        public Nullable<System.DateTime> date_dictated { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public bool delete_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abstraction_log> abstraction_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accuracy> accuracies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_log> admin_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> documents { get; set; }
        public virtual entity entity { get; set; }
        public virtual entity entity1 { get; set; }
        public virtual entity entity2 { get; set; }
        public virtual entity entity3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log> logs { get; set; }
        public virtual relationship relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_audio> job_audio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_comment> job_comment { get; set; }
        public virtual user user { get; set; }
        public virtual job_priority job_priority { get; set; }
        public virtual job_status job_status { get; set; }
        public virtual job_type job_type { get; set; }
        public virtual user user1 { get; set; }
        public virtual patient patient { get; set; }
        public virtual relationship relationship1 { get; set; }
        public virtual workflow_step workflow_step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nlp_job> nlp_job { get; set; }
    }
}
