//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<int> event_code_id { get; set; }
        public string description { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_last_modifed { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> last_modified_by { get; set; }
    
        public virtual event_code event_code { get; set; }
        public virtual job job { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
