//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_priority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public log_priority()
        {
            this.event_code = new HashSet<event_code>();
        }
    
        public int id { get; set; }
        public Nullable<int> priority_level { get; set; }
        public string description { get; set; }
        public string notify_recipient { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_last_modified { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> last_modified_by { get; set; }
        public bool delete_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_code> event_code { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
