//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class medisapien_data_path
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string CertaintyPath { get; set; }
        public string XmlPath { get; set; }
        public string XmlCertaintyPath { get; set; }
        public string XmlCodeSystemName { get; set; }
    }
}
