//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class medisapien_job
    {
        public long ID { get; set; }
        public Nullable<long> job_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string VID { get; set; }
        public string CID { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string PatFN { get; set; }
        public string PatLN { get; set; }
        public string PatMI { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string NLPOutput { get; set; }
        public string customerFilename { get; set; }
        public byte[] custInputFile { get; set; }
        public Nullable<System.DateTime> DateImported { get; set; }
    }
}
