//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationship_setting_detail
    {
        public int id { get; set; }
        public int relationship_id { get; set; }
        public int setting_detail_id { get; set; }
        public string setting_detail_value { get; set; }
        public bool locked { get; set; }
        public bool hidden { get; set; }
        public bool system_locked { get; set; }
        public bool system_hidden { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual relationship relationship { get; set; }
        public virtual setting_detail setting_detail { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
