//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public setting_detail()
        {
            this.entity_setting_detail = new HashSet<entity_setting_detail>();
            this.relationship_setting_detail = new HashSet<relationship_setting_detail>();
            this.setting_detail1 = new HashSet<setting_detail>();
        }
    
        public int id { get; set; }
        public int setting_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string default_value { get; set; }
        public int sort_order { get; set; }
        public bool locked { get; set; }
        public bool hidden { get; set; }
        public bool system_locked { get; set; }
        public bool system_hidden { get; set; }
        public Nullable<int> parent_setting_detail_id { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public bool delete_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entity_setting_detail> entity_setting_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relationship_setting_detail> relationship_setting_detail { get; set; }
        public virtual setting setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<setting_detail> setting_detail1 { get; set; }
        public virtual setting_detail setting_detail2 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
