//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackdocDbEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class speechrec_job
    {
        public int id { get; set; }
        public int audio_id { get; set; }
        public int status_id { get; set; }
        public string operation_name { get; set; }
        public string output { get; set; }
        public string postprocoutput { get; set; }
        public int created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public int last_modified_by { get; set; }
        public System.DateTime date_last_modified { get; set; }
        public bool delete_flag { get; set; }
    
        public virtual audio audio { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual speechrec_status speechrec_status { get; set; }
    }
}
